test: Migrate to Swift Testing (#14)
* test: Migrate to Swift Testing

Add swift-testing package to project
Upgrade devcontainer image to use nightly-6.0-jammy for swift-testing
    support on Linux
Convert the following XCTests to Swift Testing:
- RepoTests
- EndpointSessionTests
- EndpointTests

Move EndpointTests performance test into new EndpointPerformanceTests
    XCTestCase
Delete redundant GitHubStatsCore and associated XCTests

* test: Update GHA jobs to support new Swift Testing

Split job into macOS and Ubuntu specific jobs
Add concurrency setting to GHA so only one per branch will run at a time
Update GH actions to their latest versions
Update GH runner to latest Swift Ubuntu image
Update GH runner to macOS 15
Replace setup-swift action with xcode-select-version-action and update
    to Xcode 16 on macOS
Build tests when building package
Use --skip testGetPullRequestsPerformance to not run long running tests
Set TEST_GITHUB_TOKEN environment variable at the swift test level
Update test-reporting path to new swift-testing results file path
Add workaround for test-reporting
    issue [1169](https://github.com/actions/checkout/issues/1169)

Switch swift-testing package to use newly released v0.12.0

Update missed Swift Testing migration of XCTSkip to @Suite(.disabled())
    in EndpointTests
Change testGetPullRequestsPerformance timeout to 3 minutes

TODO: Collapse macOS and Ubuntu jobs back into one

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -13,37 +13,76 @@ on:
   pull_request:
     branches: [ "main" ]
 
+concurrency:
+  group: ci-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
-  build:
+  macos:
+    strategy:
+      fail-fast: true
+      matrix:
+        os: [macos-15]
+
     name: Build and test on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [macos-13, ubuntu-latest]
-
     steps:
-    - uses: swift-actions/setup-swift@v1
-    - uses: actions/checkout@v3
-    - name: Get swift version
-      run: swift --version # Swift 5.9
+    - uses: actions/checkout@v4
+    - name: Xcode Select Version
+      uses: mobiledevops/xcode-select-version-action@v1
+      with:
+        xcode-select-version: 16
     - name: Get macOS version
       run: sw_vers
-      if: startsWith( matrix.os, 'macos' )
-    - name: Set TEST_GITHUB_TOKEN env variable
-      shell: bash
-      env:
-        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
-      run: |
-        echo "$TEST_GITHUB_TOKEN" > $HOME/.env
+    - name: Get xcodebuild version
+      run: xcodebuild -version 
+    - name: Get swift version
+      run: swift --version
     - name: Build
-      run: swift build
+      run: swift build --build-tests
     - name: Run tests
-      run: swift test --parallel --xunit-output=results.xml
+      run: swift test --skip testGetPullRequestsPerformance --parallel --xunit-output=results.xml
+      env:
+        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}  
     - name: Report test results
-      uses: phoenix-actions/test-reporting@v8
+      uses: phoenix-actions/test-reporting@v15
       id: test-report
       if: success() || failure()    # run this step even if previous step failed
       with:
         name: Swift tests on ${{ matrix.os }}
-        path: results.xml
+        path: results-swift-testing.xml
         reporter: java-junit
+ 
+  ubuntu:
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+
+    name: Build and test on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    container:
+      image: swift:latest
+      env:
+        TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
+    steps:
+    - uses: actions/checkout@v4
+    - name: Get Linux version
+      run: uname -a
+    - name: Get swift version
+      run: swift --version
+    - name: Build
+      run: swift build --build-tests
+    - name: Run tests
+      run: swift test --skip testGetPullRequestsPerformance --parallel --xunit-output=results.xml
+    - name: Workaround for test-reporting issue 1169
+      run: git config --system --add safe.directory /__w/github-stats/github-stats
+      if: success() || failure()    # run this step even if previous step failed
+    - name: Report test results
+      uses: phoenix-actions/test-reporting@v15
+      id: test-report
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Swift tests on ${{ matrix.os }}
+        path: results-swift-testing.xml
+        reporter: java-junit
+
